apiVersion: v1
kind: PersistentVolume
metadata:
 name: nexuspv
spec:
 capacity:
   storage: 100Gi
 volumeMode: Filesystem
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: slow
 mountOptions:
   - hard
   - nfsvers=4.1
 nfs:
   path: /data/k8s-pvs/pv015
   server: nfsserver.example.com